---
# Documentation: https://docs.docker.com/compose/compose-file/compose-file-v3/

version: '3.8'
services:
  musicblocks:
    build: ./
    image: ghcr.io/sugarlabs/musicblocks:4-dev
    env_file:
      - ./env/development.env
    ports:
      - '5173:5173' # development server
      - '4173:4173' # production preview server
    volumes:
      - ./:/app/
    container_name: musicblocks-4-dev
    stdin_open: true
    tty: true
